### ISSUE TITLE
Conda 'Access is denied' error while installing Numpy

### ISSUE THREAD

**Issue by anaknickerbocker** [aubio/aubio#218] opened 2018-12-07 15:58 UTC
I tried installing aubio with conda:
```
$ conda config --add channels conda-forge
$ conda install -c conda-forge aubio
```

I get the following error:
```
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while uninstalling package 'defaults::numpy-1.15.1-py37ha559c80_0'.
PermissionError(13, 'Access is denied')
Attempting to roll back.

Rolling back transaction: done

PermissionError(13, 'Access is denied')
```

**Comment by piem** [comment] 2018-12-07 16:13
hello @anaknickerbocker 

Arg, this is probably caused by conda-forge/aubio-feedstock#15 when upgrading aubio from `0.4.8-py27h7273d18_0` to `0.4.8-py27hc997a72_1`.

Please try uninstalling aubio, then re-installing again:

    $ conda remove aubio
    $ conda install -c conda-forge aubio

and let us know how it goes.

thanks, piem

**Comment by piem** [comment] 2018-12-07 16:32
did you (or someone else) install aubio or numpy with root privileges? these could help:

    $ sudo conda remove -c conda-forge aubio
    $ sudo conda remove numpy-1.15.1-py37ha559c80_0

**Comment by anaknickerbocker** [comment] 2018-12-07 16:37
I'm on Windows 10. I tried running Anaconda Prompt "As Administrator" and ran those commands, but got the same "PackagesNotFoundError" for both.

**Comment by piem** [comment] 2018-12-07 16:45
could it be that you have a process using that numpy binary at the moment?

Using `conda list`, you should be able to find which numpy or aubio package is still installed.

Adding the `-f/--force` option to `conda remove` and/or `conda install` might help too.

**Comment by piem** [comment] 2018-12-09 15:59
hi @anaknickerbocker 

any progress on this?

thanks, piem

**Comment by anaknickerbocker** [comment] 2018-12-10 20:33
@piem sorry for the delay!

I don't have any processes using numpy.

I've never had aubio installed before, so this is a first-time install.

using `-f/--force` on the `conda remove` and `conda install` commands produce the same results as before.

- `conda remove`: "PackagesNotFoundError"
- `conda install`:
  ```
  ERROR conda.core.link:_execute(502): An error occurred while uninstalling package 'defaults::numpy-1.15.1-py37ha559c80_0'.
  PermissionError(13, 'Access is denied')
   ```

Thanks!

**Comment by piem** [comment] 2018-12-10 21:53
@anaknickerbocker thanks for the info

@conda-forge/core any idea of a workaround for this one?

See also conda-forge/aubio-feedstock#15

thanks, piem

**Comment by piem** [comment] 2018-12-11 15:31
hi again,

I asked on the conda-forge.github.io gitter channel, someone mentioned trying:

    conda create -n aubio aubio

to force conda to pick the latest version of aubio. Could you try that @anaknickerbocker ?

thanks, piem

**Comment by piem** [comment] 2019-01-04 16:32
hi @anaknickerbocker 

I hope this is sorted now, closing this issue. Please provide more info if you still encounter issues.

best, piem

**Closed by piem** 2019-01-04 16:32 UTC
