### ISSUE TITLE
dyld: Library not loaded 

### ISSUE THREAD

**Issue by adamski** [aubio/aubio#29] opened 2015-10-05 19:33 UTC
I’ve been trying to debug a crash on launch on device (iOS) which seems to be coming from aubio:

dyld: Library not loaded: /usr/local/lib/libaubio.4.dylib
  Referenced from: /var/mobile/Applications/CCFF68BA-4186-421E-A07E-D5482B654D98/MyApp.app/MyApp
  Reason: image not found

This has been happening since I updated to Xcode 7. I am also using Swift in my project. I’ve updated to aubio 0.4.2. I'm using the iOS Universal framework download.

If I set aubio as an optional framework it loads the rest of the app but then crashes on new_aubio_pitch()

**Comment by piem** [comment] 2015-10-06 12:26
duplicate of #30

**Closed by piem** 2015-10-06 12:26 UTC
