### ISSUE TITLE
Windows 10 Python3.6 "pip install aubio==0.4.9" fails

### ISSUE THREAD

**Issue by peter-volkov** [aubio/aubio#248] opened 2019-05-05 21:46 UTC
Python 3.6.2
pip 9.0.1
setuptools 41.0.1

pip install aubio==0.4.9

```
Collecting aubio
  Using cached https://files.pythonhosted.org/packages/cd/80/302d89240603e5347c7f8026c8b02c59f8dfaec66c91a743d82de7c86006/aubio-0.4.9.tar.gz
Requirement already satisfied: numpy in c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages (from aubio)
Installing collected packages: aubio
  Running setup.py install for aubio: started
    Running setup.py install for aubio: finished with status 'error'
    Complete output from command c:\users\username\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\username\\AppData\\Local\\Temp\\pip-build-4srgqirc\\aubio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\username\AppData\Local\Temp\pip-quvg4xhi-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\aubio
    copying python\lib\aubio\cmd.py -> build\lib.win32-3.6\aubio
    copying python\lib\aubio\cut.py -> build\lib.win32-3.6\aubio
    copying python\lib\aubio\midiconv.py -> build\lib.win32-3.6\aubio
    copying python\lib\aubio\slicing.py -> build\lib.win32-3.6\aubio
    copying python\lib\aubio\__init__.py -> build\lib.win32-3.6\aubio
    running build_ext
    checking for aubio = 0.4.9
    Running "pkg-config --libs --cflags aubio = 0.4.9" failed: FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
    Info: aubio 0.4.9 was not found by pkg-config
    Info: looking for *optional* additional packages
    checking for libavcodec
    Running "pkg-config --libs --cflags libavcodec" failed: FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
    checking for libavformat
    Running "pkg-config --libs --cflags libavformat" failed: FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
    checking for libavutil
    Running "pkg-config --libs --cflags libavutil" failed: FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
    checking for libswresample
    Running "pkg-config --libs --cflags libswresample" failed: FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
    checking for libavresample
    Running "pkg-config --libs --cflags libavresample" failed: FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
    checking for sndfile
    Running "pkg-config --libs --cflags sndfile" failed: FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
    checking for samplerate
    Running "pkg-config --libs --cflags samplerate" failed: FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
    Info: libaubio was not installed or built locally with waf, adding src/
    Running command: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x86\cl.exe -E -DAUBIO_UNSTABLE=1 -Isrc src\aubio.h
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\username\AppData\Local\Temp\pip-build-4srgqirc\aubio\setup.py", line 95, in <module>
        'aubiocut = aubio.cut:main',
      File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\username\appdata\local\programs\python\python36-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\username\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\username\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\username\appdata\local\programs\python\python36-32\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\username\appdata\local\programs\python\python36-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\username\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\username\appdata\local\programs\python\python36-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\username\appdata\local\programs\python\python36-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\username\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\username\appdata\local\programs\python\python36-32\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "c:\users\username\appdata\local\programs\python\python36-32\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "c:\users\username\appdata\local\programs\python\python36-32\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "python\lib\moresetuptools.py", line 192, in build_extension
        usedouble=enable_double)
      File "python\lib\gen_external.py", line 271, in generate_external
        c_declarations = get_c_declarations(header, usedouble=usedouble)
      File "python\lib\gen_external.py", line 101, in get_c_declarations
        cpp_output = get_cpp_output(header=header, usedouble=usedouble)
      File "python\lib\gen_external.py", line 129, in get_cpp_output
        % err_output.decode('utf8'))
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 0: invalid start byte
    
    ----------------------------------------

```

Any clues?
Russian text there "Не удается найти указанный файл" means "cannot find specified file"
It seems that something happens with pkg-config tool.
It installs well for python27 via pip

**Comment by peter-volkov** [comment] 2019-05-05 21:55
for Python3.7 it is 

```
Collecting aubio
  Using cached https://files.pythonhosted.org/packages/cd/80/302d89240603e5347c7f8026c8b02c59f8dfaec66c91a743d82de7c86006/aubio-0.4.9.tar.gz
Requirement already satisfied: numpy in c:\users\username\appdata\local\programs\python\python37-32\lib\site-packages (from aubio) (1.16.3)
Installing collected packages: aubio
  Running setup.py install for aubio: started
    Running setup.py install for aubio: finished with status 'error'
    Complete output from command c:\users\username\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-6kikyjvm\\aubio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\username\AppData\Local\Temp\pip-record-_74e929l\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\aubio
    copying python\lib\aubio\cmd.py -> build\lib.win32-3.7\aubio
    copying python\lib\aubio\cut.py -> build\lib.win32-3.7\aubio
    copying python\lib\aubio\midiconv.py -> build\lib.win32-3.7\aubio
    copying python\lib\aubio\slicing.py -> build\lib.win32-3.7\aubio
    copying python\lib\aubio\__init__.py -> build\lib.win32-3.7\aubio
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\username\AppData\Local\Temp\pip-install-6kikyjvm\aubio\setup.py", line 95, in <module>
        'aubiocut = aubio.cut:main',
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "python\lib\moresetuptools.py", line 192, in build_extension
        usedouble=enable_double)
      File "python\lib\gen_external.py", line 271, in generate_external
        c_declarations = get_c_declarations(header, usedouble=usedouble)
      File "python\lib\gen_external.py", line 101, in get_c_declarations
        cpp_output = get_cpp_output(header=header, usedouble=usedouble)
      File "python\lib\gen_external.py", line 129, in get_cpp_output
        % err_output.decode('utf8'))
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 0: invalid start byte
    checking for aubio = 0.4.9
    Running "pkg-config --libs --cflags aubio = 0.4.9" failed: FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
    Info: aubio 0.4.9 was not found by pkg-config
    Info: looking for *optional* additional packages
    checking for libavcodec
    Running "pkg-config --libs --cflags libavcodec" failed: FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
    checking for libavformat
    Running "pkg-config --libs --cflags libavformat" failed: FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
    checking for libavutil
    Running "pkg-config --libs --cflags libavutil" failed: FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
    checking for libswresample
    Running "pkg-config --libs --cflags libswresample" failed: FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
    checking for libavresample
    Running "pkg-config --libs --cflags libavresample" failed: FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
    checking for sndfile
    Running "pkg-config --libs --cflags sndfile" failed: FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
    checking for samplerate
    Running "pkg-config --libs --cflags samplerate" failed: FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
    Info: libaubio was not installed or built locally with waf, adding src/
    Running command: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x86\cl.exe -E -DAUBIO_UNSTABLE=1 -Isrc src\aubio.h
    
    ----------------------------------------

```

**Comment by piem** [comment] 2019-05-06 05:00
hi @peter-volkov 

thanks for your report. It doesn't seem that `pkg-config` being not found is the issue here.

This seems quite simliar to #247, although the `UnicodeDecodeError` is a bit suspicious. Could you check the instructions given there and make sure a compiler is found?

thanks, piem

**Comment by piem** [comment] 2019-05-06 20:07
hi again @peter-volkov,

closing this issue as a duplicate of #247. This is a decoding issue. With your help, we may solve it!

cheers, piem

**Closed by piem** 2019-05-06 20:07 UTC
